name: scarabei_desktop_red
description: Collection of open source reusable Dart components
version: 0.0.4
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
   scarabei_api: "^0.0.4"
   scarabei_desktop_api: "^0.0.4"
   scarabei_red: "^0.0.4"
#  scarabei_desktop_api:
#    path: ../scarabei-desktop-api
#  scarabei_red:
#    path: ../scarabei-red


dev_dependencies:
  test: ^0.12.0
