name: scarabei_flutter_reyer
description: Collection of open source reusable Dart components
version: 1.0.0
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  scarabei:
    path: ../scarabei
  scarabei_reyer:
    path: ../scarabei_reyer
#  scarabei: "^1.0.0"
#  flutter: "^0.0.20"




dev_dependencies:
  test: ^0.12.0
