name: scarabei_flutter_reyer
description: Collection of open source reusable Dart components
version: 3.2.0
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  scarabei: ^3.2.0
#

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.21
  scarabei_reyer: ^3.2.0
#  scarabei_reyer:
#    path: ../scarabei_reyer

dependency_overrides:
#  scarabei:
#    path: ../scarabei



