name: scarabei_flutter_reyer
description: Collection of open source reusable Dart components
version: 1.1.1
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

dependencies:
  flutter:
    sdk: flutter
  scarabei:
    path: ../scarabei
  scarabei_reyer:
    path: ../scarabei_reyer
#  scarabei: ">=1.1.1 <2.0.0"
#  scarabei_reyer: ">=1.1.1 <2.0.0"
