name: scarabei_flutter_reyer
description: Collection of open source reusable Dart components
version: 2.1.0
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  scarabei: ^2.1.0
  scarabei_reyer: ^2.1.0

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.21

dependency_overrides:
  scarabei:
    path: ../scarabei
  scarabei_reyer:
    path: ../scarabei_reyer


