name: scarabei_android_reyer
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: JCode <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  scarabei_android_api:
    path: ../scarabei-android-api
  scarabei_reyer:
    path: ../scarabei-reyer

dev_dependencies:
  test: ^0.12.0
