name: scarabei_desktop_red_example
description: A sample command-line application.
version: 0.0.4
#homepage: https://www.example.com
#author: JCode <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
#   scarabei_desktop_red: "^0.0.4"
  scarabei_api:
    path: ../scarabei-api
  scarabei_desktop_red:
    path: ../scarabei-desktop-red


dev_dependencies:
  test: ^0.12.0
