name: scarabei_reyer
description: Collection of open source reusable Dart components
version: 3.2.0
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  scarabei: ^3.2.0
  crypto: ^2.0.2
  path: ^1.4.2
  logging: ^0.11.3+1

dependency_overrides:
#  scarabei:
#    path: ../scarabei

