name: scarabei_reyer
description: Collection of open source reusable Dart components
version: 1.1.1
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>


dependencies:
  scarabei:
    path: ../scarabei
#  scarabei: ">=1.1.1 <2.0.0"
  crypto: ">=2.0.2 <3.0.0"
  path: ">=1.4.2 <3.0.0"
  logging: "^0.11.3+1"
