name: scarabei_reyer
description: Collection of open source reusable Dart components
version: 0.0.2
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:

dependencies:
#  scarabei_api: "^0.0.2"
  crypto: "^2.0.1"
  path: ^1.4.2
  scarabei_api:
    path: ../scarabei-api


dev_dependencies:
  test: ^0.12.0
